// flow-typed signature: 172ec6be28c5ce248f8f3f503c9bd422
// flow-typed version: <<STUB>>/strangelog_v^2.0.2/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strangelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strangelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strangelog/lib/actions' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/addEntry' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/bumpNextVersion' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/changelogInfo' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/connectChangelog' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/generate' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/getChangelogData' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/getPossibleNextVersions' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/getSortedChangelogVersions' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/migrate' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/migrations/0_toSemVerDirectories' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/migrations/1_toFSFriendlyEntryFileName' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/migrations' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/types' {
  declare module.exports: any;
}

declare module 'strangelog/lib/api/utils' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli/cli' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli/commands/add' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli/commands/bump' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli/commands/generate' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli/commands/migrate' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli' {
  declare module.exports: any;
}

declare module 'strangelog/lib/cli/types' {
  declare module.exports: any;
}

declare module 'strangelog/lib/getProjectConfig' {
  declare module.exports: any;
}

declare module 'strangelog/lib' {
  declare module.exports: any;
}

declare module 'strangelog/lib/reducer' {
  declare module.exports: any;
}

declare module 'strangelog/lib/templates/defaultTemplate' {
  declare module.exports: any;
}

declare module 'strangelog/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strangelog/index' {
  declare module.exports: $Exports<'strangelog'>;
}
declare module 'strangelog/index.js' {
  declare module.exports: $Exports<'strangelog'>;
}
declare module 'strangelog/lib/actions.js' {
  declare module.exports: $Exports<'strangelog/lib/actions'>;
}
declare module 'strangelog/lib/api/addEntry.js' {
  declare module.exports: $Exports<'strangelog/lib/api/addEntry'>;
}
declare module 'strangelog/lib/api/bumpNextVersion.js' {
  declare module.exports: $Exports<'strangelog/lib/api/bumpNextVersion'>;
}
declare module 'strangelog/lib/api/changelogInfo.js' {
  declare module.exports: $Exports<'strangelog/lib/api/changelogInfo'>;
}
declare module 'strangelog/lib/api/connectChangelog.js' {
  declare module.exports: $Exports<'strangelog/lib/api/connectChangelog'>;
}
declare module 'strangelog/lib/api/generate.js' {
  declare module.exports: $Exports<'strangelog/lib/api/generate'>;
}
declare module 'strangelog/lib/api/getChangelogData.js' {
  declare module.exports: $Exports<'strangelog/lib/api/getChangelogData'>;
}
declare module 'strangelog/lib/api/getPossibleNextVersions.js' {
  declare module.exports: $Exports<'strangelog/lib/api/getPossibleNextVersions'>;
}
declare module 'strangelog/lib/api/getSortedChangelogVersions.js' {
  declare module.exports: $Exports<'strangelog/lib/api/getSortedChangelogVersions'>;
}
declare module 'strangelog/lib/api/index' {
  declare module.exports: $Exports<'strangelog/lib/api'>;
}
declare module 'strangelog/lib/api/index.js' {
  declare module.exports: $Exports<'strangelog/lib/api'>;
}
declare module 'strangelog/lib/api/migrate.js' {
  declare module.exports: $Exports<'strangelog/lib/api/migrate'>;
}
declare module 'strangelog/lib/api/migrations/0_toSemVerDirectories.js' {
  declare module.exports: $Exports<'strangelog/lib/api/migrations/0_toSemVerDirectories'>;
}
declare module 'strangelog/lib/api/migrations/1_toFSFriendlyEntryFileName.js' {
  declare module.exports: $Exports<'strangelog/lib/api/migrations/1_toFSFriendlyEntryFileName'>;
}
declare module 'strangelog/lib/api/migrations/index' {
  declare module.exports: $Exports<'strangelog/lib/api/migrations'>;
}
declare module 'strangelog/lib/api/migrations/index.js' {
  declare module.exports: $Exports<'strangelog/lib/api/migrations'>;
}
declare module 'strangelog/lib/api/types.js' {
  declare module.exports: $Exports<'strangelog/lib/api/types'>;
}
declare module 'strangelog/lib/api/utils.js' {
  declare module.exports: $Exports<'strangelog/lib/api/utils'>;
}
declare module 'strangelog/lib/cli/cli.js' {
  declare module.exports: $Exports<'strangelog/lib/cli/cli'>;
}
declare module 'strangelog/lib/cli/commands/add.js' {
  declare module.exports: $Exports<'strangelog/lib/cli/commands/add'>;
}
declare module 'strangelog/lib/cli/commands/bump.js' {
  declare module.exports: $Exports<'strangelog/lib/cli/commands/bump'>;
}
declare module 'strangelog/lib/cli/commands/generate.js' {
  declare module.exports: $Exports<'strangelog/lib/cli/commands/generate'>;
}
declare module 'strangelog/lib/cli/commands/migrate.js' {
  declare module.exports: $Exports<'strangelog/lib/cli/commands/migrate'>;
}
declare module 'strangelog/lib/cli/index' {
  declare module.exports: $Exports<'strangelog/lib/cli'>;
}
declare module 'strangelog/lib/cli/index.js' {
  declare module.exports: $Exports<'strangelog/lib/cli'>;
}
declare module 'strangelog/lib/cli/types.js' {
  declare module.exports: $Exports<'strangelog/lib/cli/types'>;
}
declare module 'strangelog/lib/getProjectConfig.js' {
  declare module.exports: $Exports<'strangelog/lib/getProjectConfig'>;
}
declare module 'strangelog/lib/index' {
  declare module.exports: $Exports<'strangelog/lib'>;
}
declare module 'strangelog/lib/index.js' {
  declare module.exports: $Exports<'strangelog/lib'>;
}
declare module 'strangelog/lib/reducer.js' {
  declare module.exports: $Exports<'strangelog/lib/reducer'>;
}
declare module 'strangelog/lib/templates/defaultTemplate.js' {
  declare module.exports: $Exports<'strangelog/lib/templates/defaultTemplate'>;
}
declare module 'strangelog/lib/types.js' {
  declare module.exports: $Exports<'strangelog/lib/types'>;
}
